# Generated by Django 2.1.15 on 2024-06-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carinsurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='car_policy',
            new_name='policy',
        ),
    ]
