# Generated by Django 2.1.15 on 2024-07-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinsurance', '0002_auto_20240629_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='damage',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Moderate', max_length=100),
        ),
    ]
