# Generated by Django 2.1.15 on 2024-07-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinsurance', '0003_claim_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpolicy',
            name='sum_assurance',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
