# Generated by Django 2.1.15 on 2024-07-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinsurance', '0004_carpolicy_sum_assurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpolicy',
            name='amount_claimed',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
