# Generated by Django 2.1 on 2024-07-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinsurance', '0006_auto_20240713_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardefect',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=100),
        ),
    ]
