# Generated by Django 2.1 on 2024-07-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinsurance', '0007_auto_20240713_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardefect',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
